version: "3.7"

services:
  crdb:
    image: cockroachdb/cockroach:v23.2.5
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
